const NAVIGATOR = {
    START: 'NAVIGATOR_START',
    LOGIN: 'NAVIGATOR_LOGIN',
    DRAWER: 'NAVIGATOR_DRAWER',
    PASSWORD_RECOVERY: 'NAVIGATION_PASSWORD_RECOVERY',
};
const LOGIN_STACK = {
    MAIN: 'MAIN',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
};

const REGISTER = {
    REGISTER: 'REGISTER',
}

export default {
    NAVIGATOR,
    LOGIN_STACK,
    REGISTER
}