const NAVIGATOR = {
    START: 'NAVIGATOR_START',
    LOGIN: 'NAVIGATOR_LOGIN',
    DRAWER: 'NAVIGATOR_DRAWER',
    PASSWORD_RECOVERY: 'NAVIGATION_PASSWORD_RECOVERY',
};
const LOGIN_STACK = {
    MAIN: 'MAIN',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
    CONFIRM_RECOVERY: 'CONFIRM_RECOVERY',
    NEW_PASSWORD: 'NEW_PW',
};

const REGISTER = {
    REGISTER: 'REGISTER',
    CONFIRM_NEW_USR_CODE: 'CONFIRM_NEW_USR_CODE',
};

const OWNER = {
    OWNER_HOME: 'OWNER_HOME',
    OWNER_ADD_CINE: 'OWNER_ADD_CINE',
    OWNER_MODIFY_CINE: 'OWNER_MODIFY_CINE',
    OWNER_ROOMS: 'OWNER_ROOMS',
    OWNER_ADD_ROOM: 'OWNER_ADD_ROOM',
};

export default {
    NAVIGATOR,
    LOGIN_STACK,
    REGISTER,
    OWNER,
}